language: python

# needed to use trusty
sudo: required

dist: trusty

branches:
  only:
    - master

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run coverage run --source=twstock -m unittest

after_success:
  - pipenv run coveralls
  - pipenv run codecov
